name: searxng

services:
  core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./core-config/:/etc/searxng/:Z
      - ./templates:/usr/local/searxng/searx/templates
      - searxng-core-data:/var/cache/searxng/
    networks:
      - searxng-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${SEARXNG_PORT:-8080}/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - searxng-valkey-data:/data/
    networks:
      - searxng-network
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  searxng-core-data:
  searxng-valkey-data:

networks:
  searxng-network:
    driver: bridge
