name: searxng

services:
  core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./core-config/:/etc/searxng/:Z
      - searxng-core-data:/var/cache/searxng/
    networks:
      - searxng-network

  valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - searxng-valkey-data:/data/
    networks:
      - searxng-network

  dozzle:
    container_name: searxng-dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - searxng-dozzle-data:/data
    networks:
      - searxng-network
    environment:
      # Define base path of dozzle
      - DOZZLE_BASE=/logs
      # 
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      - DOZZLE_ENABLE_ACTIONS=true
      #
      # Uncomment to allow access to container shells. See https://dozzle.dev/guide/shell
      - DOZZLE_ENABLE_SHELL=true
      #
      # Uncomment to enable authentication. See https://dozzle.dev/guide/authentication
      # - DOZZLE_AUTH_PROVIDER=simple

  nginx:
    container_name: searxng-nginx
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    env_file: ./.env
    environment:
      - DOMAIN_NAME=${SUBDOMAIN}.${DOMAIN}
      - SEARXNG_URL=http://core:${SEARXNG_PORT:-8080}/
      - DOZZLE_URL=http://dozzle:8080/logs/
    command: >
      /bin/sh -c "envsubst '$${DOMAIN_NAME} $${SEARXNG_URL} $${DOZZLE_URL}'
      < /etc/nginx/conf.d/default.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
    networks:
      - searxng-network
    depends_on:
      - core
      - valkey
      - dozzle

volumes:
  searxng-core-data:
  searxng-valkey-data:
  searxng-dozzle-data:

networks:
  searxng-network:
    driver: bridge
